name: Deploy
on: 
  push:
    branches:
      - master
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      
    - name: Deploy
      run: |
       npm install -g serverless 
       npm install serverless-offline 
       serverless config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

       make deploy
